import { restTransformAt } from "@/app/components/motion-studio/engine/transform";
import type { Clip, StudioDoc } from "@/app/components/motion-studio/types";

const RUNTIME = "@/app/components/motion-studio";

const toPascal = (s: string) =>
  s
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(" ")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("") || "Animation";

function stripLottieData(clip: Clip): Clip {
  if (clip.type !== "lottie") return clip;
  return { ...clip, data: { note: "Load this Lottie JSON from your own import" } };
}

/** A single exported clip has no parent to ride, so its resting stage position is baked in. */
function detachForExport(doc: StudioDoc, clip: Clip): Clip {
  if (!clip.parentId) return clip;
  const rest = restTransformAt(doc, clip.id);
  return { ...clip, parentId: null, x: rest.x, y: rest.y };
}

/**
 * Generates a drop-in React component for one clip. It renders the clip with
 * its current settings baked in and runs its own clock, so a dev only needs
 * the shared runtime folder plus this file.
 */
export function clipComponentCode(doc: StudioDoc, clip: Clip): string {
  const name = toPascal(clip.name);
  const local = { ...stripLottieData(detachForExport(doc, clip)), start: 0 };
  return `"use client";

import {
  ClipView,
  clipDuration,
  useStudioClock,
  type Clip,
  type StudioDoc,
} from "${RUNTIME}";

// Generated by the motion studio from "${doc.name}" › "${clip.name}".
// Tune values here or re-export from the studio. Positions are stage pixels
// relative to the wrapping element; STAGE sets the canvas the clip was
// designed on so the coordinates line up.
const CLIP: Clip = ${JSON.stringify(local, null, 2)};

const STAGE: StudioDoc = {
  version: ${doc.version},
  name: "${doc.name}",
  stage: ${JSON.stringify(doc.stage)},
  clips: [CLIP],
};

export function ${name}({
  loop = ${clip.type === "sprite" && clip.loop ? "true" : "false"},
  autoplay = true,
}: {
  loop?: boolean;
  autoplay?: boolean;
}) {
  const { time } = useStudioClock(clipDuration(CLIP) + 0.5, { loop, autoplay });
  return (
    <div
      className="relative overflow-hidden"
      style={{ width: STAGE.stage.width, height: STAGE.stage.height }}
    >
      <ClipView clip={CLIP} doc={STAGE} time={time} />
    </div>
  );
}
`;
}

/** Generates a component that plays the whole composition. */
export function docComponentCode(doc: StudioDoc): string {
  const name = toPascal(doc.name);
  const clean: StudioDoc = { ...doc, clips: doc.clips.filter((c) => c.enabled).map(stripLottieData) };
  return `"use client";

import {
  StageCanvas,
  docDuration,
  useStudioClock,
  type StudioDoc,
} from "${RUNTIME}";

// Generated by the motion studio. Scale the stage with the \`zoom\` prop or
// wrap it in a container with \`transform: scale()\` to fit a layout.
const DOC: StudioDoc = ${JSON.stringify(clean, null, 2)};

export function ${name}({ zoom = 1, loop = false }: { zoom?: number; loop?: boolean }) {
  const { time } = useStudioClock(docDuration(DOC), { autoplay: true, loop });
  return <StageCanvas doc={DOC} time={time} zoom={zoom} />;
}
`;
}

export const HANDOFF_NOTES = `Handoff
1. The runtime lives in src/app/components/motion-studio (engine, clip renderers, StageCanvas). It has no dependency on the admin editor.
2. Drop the generated component anywhere in the app. It runs its own clock; pass loop / autoplay as needed.
3. To control playback yourself, call useStudioClock(duration) and pass its time MotionValue to StageCanvas or ClipView.
4. Every value in the generated CLIP / DOC object is editable by hand. Re-export from the studio to replace it.
5. Lottie clips export without their JSON payload. Import the .json in your component and assign it to \`data\`.
6. Attached clips keep their \`parentId\`; the runtime composes each child's transform from its parent every frame. A child's x / y are its offset in the parent's frame, so change those to move it relative to the parent. A single-clip export is detached with its resting stage position baked in.`;
